### ISSUE TITLE
PLEASE: How can I build an STATIC BINARY?

### ISSUE THREAD

**Issue by Adeliscod** [muecoin/MUECore#2]
I need to compile the app in a static form where the binary that outputs doesn't require the installation of more libraries. For example:

": error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory." This happens when I move the binary and try to compile it in another server.

Thanks

**Comment by c44c** [comment]
Sorry for the late response, but you can't compile a binary on one server and attempt to move it to another that doesn't have the supporting libraries. It not supported in the Bitcoin supporting libraries that MUE is built upon.

You could attempt to try to make a static compile, but we do not support that at this point, and the build will likely fail to run.

It is in our planned release to make packages for the popular Linux systems or check the option of making a flatpack image. No ETA on these options though.
